In [2]:
import matplotlib  # 시각화 패키지
import numpy as np  # 별칭 class
print(np.__version__) # 상위 object가 가지고 있는 속성( __함수__)
def pprint(arr):   # ndarray : numpy의 기본 데이터 배열 
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension: {}, dtype: {}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)
    # 숫자의 default 타입 : int32형
arr = [1,2,3] # 리스트
a = np.array([1,2,3])   #ndarray 생성함수 ( 매개변수 : 리스트 )
pprint(a)

arr = [1.0,2.0,3.0]
b = np.array([1,2,3])
pprint(b)


1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension: 1, dtype: int32
Array's Data:
 [1 2 3]
type:<class 'numpy.ndarray'>
shape:(3,), dimension: 1, dtype: int32
Array's Data:
 [1 2 3]


In [5]:
# 인스턴스 상태
a = np.array([0,1,2,3,4,5,6,7,8,9])  #ndarray 생성
print(id(a))  # 주소값 확인
print(a.size)  # 데이터 개수
print(a.astype(np.float32))  # astype : 데이터 타입 변경 , numpy : 행중심, 동질적 데이터
print(a.dtype.itemsize*a.size)  #  전체 메모리 사이즈 ( 바이트 ) 
# iterator     for in range => list 생성
a = np.arange(100)  # arange => ndarray 생성
a

1745568620096
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
print(np.zeros((3,4)))
print(np.ones((2,3,4), dtype = np.int16))  # 3차원 :  2면, 3행 , 4열
print(np.full((2,2),7))
print(np.eye(4))       # 대각행렬 identity 행렬연산에서 항등원 
print(np.empty((4,2)))   # 쓰레기값 ( 데이터를 지우면 주소를 지우는 것, 메모리에는 쓰레기값으로 남아 있음 )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[4.24399158e-313 1.69759663e-313]
 [4.88059032e-313 2.33419537e-313]
 [4.45619116e-313 1.90979621e-313]
 [4.66839074e-313 2.12199579e-313]]


In [14]:
a = np.arange(0,100,10)
print(a)

indices = [1, 5 , -1] # 리스트
print(indices)
b = a[indices]  #a[1,5,-1]   # 리스트를 첨자로 사용 
print(a)
print(b)
c = a[[1,5,-1]]
print(c)



[ 0 10 20 30 40 50 60 70 80 90]
[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]
[10 50 90]
[10]


In [21]:
a = np.arange(11, 36)  #1차원 생성
print(a)
a.shape=(5,5)
print(a)
print(type(a))
print(a.dtype)  # ndarray의 속성
print(a.size)   # 크기
print(a.shape)  # 차수 (5,5)
print(a.ndim)   # 차원 : 2차원
print(a.nbytes) # 100바이트  == 25 * 4byte
print(a.strides) # (20,4)  == ( 다음 열의 데이터는 몇 바이트를 건너뛰어야 하는가 , 다음 행은 몇 바이트를 건너뛰어야 하는가 )
                                 


#a = np.arange(11, 35)  #개수가 안맞아서 오류가 나옴 ( 5 * 5 = 25 )
#print(a)
#a.shape=(5,5)
#print(a)
#print(type(a))



[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [24]:
arr = np.arange(10)
print(type(arr))
print(arr.dtype)
print(arr)
print(arr[5])
print(arr[5:8])  # 마지막은 포함하지 않는다
arr[5:8] = 12  # 데이터 update
print(arr)
print(arr[1:6])

<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[ 1  2  3  4 12]


In [27]:
# numpy에서는 첨자를 생락할 수 없음 (,:1) 표현 불가  * 모든행 :로 표시 ex) (:,2)
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)  
print(arr2d[0])  #행우선 : 행
print(arr2d[0][2]) 
print(arr2d[0,2])
print(arr2d[:2]) # 0, 1행
print(arr2d[:2,1:])
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1] = 0
arr2d[:2,:1] = 0
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [28]:
# 실제 저장은 메모리상에 일렬로 저장됨 . 사람이 데이터를 다루는 것은 입체로.
# 행렬연산에서 앞의 행렬열수와 뒤의 행렬 행수를 일치 시켜야 행렬곱이 가능
print("스트라이드의 값", np.ones((3,4,5), dtype = np.float64).strides)
# (160, 40 ,8)  : 단일데이터 float64 = 8바이트  / 한 행 5 * 8 = 40  / 다음 면 5열 *8행 *8 바이트 = 160

스트라이드의 값 (160, 40, 8)


In [40]:
# 문제
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  # (2,2,3)
print(arr3d)
print("첫 면은 ",arr3d[0])
print("첫 면 첫 행은 ", arr3d[0][0])
print("첫 면 첫행 첫 요소는 ", arr3d[0,0,0]) #== arr3d[0][0][0]
#8 출력
print(arr3d[1,0,1])
#12 출력
print(arr3d[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
첫 면은  [[1 2 3]
 [4 5 6]]
첫 면 첫 행은  [1 2 3]
첫 면 첫행 첫 요소는  1
8
12


In [45]:
# 백업이 안됨 : 대입하면 같은 주소를 가리키기 때문에 값을 바꾸면 데이터가 바뀜
old_values = arr3d  # 대입  : 주소를 복사 
arr3d[0] = 42       
print("값의 변경 후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)  # ==> 원본이 사라짐


# copy 함수로 복사
old_values = arr3d.copy()
arr3d[1] = 42
print("값의 변경 후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[42 42 42]
  [42 42 42]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
Z = np.arange(36)
print(Z)
Z = Z.reshape((6,6))
print(Z)
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [54]:
arr = np.arange(32).reshape((8,4))
print(arr)
print("================")
print(arr[[1,5,7,2]])  # 행중심 
print("================") 
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print("================")
print(arr[[1,5,7,2],[0,3,1,2]]) #1행 0열 / 5행 3열 ....
print("================")
# fancy 인덱싱
print(arr[[1,5,7,2]][:,[0,1,2,3]])
print("================")
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [74]:
arr = []
for i in range(6) :
    ad = []
    for j in range(6):
        ad.append(i*10 + j)
    arr.append(ad)
print(arr)
print("================")
arr = np.array(arr)
print(arr)
print("================")

print(arr[[0,2,5],[2]])
print("================")

print(arr[[0,1,2,3,4],[1,2,3,4,5]])
print("================")

print(arr[[3,4,5]])
print("================")

print(arr[[3,4,5]][:,[0,2,5]])

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ 2 22 52]
[ 1 12 23 34 45]
[[30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [90]:
print(arr[[0],[3,4]])
print(arr[[0,1,2,3,4,5],2]) # == print(arr[:,2])
print(arr[[2,4]][:,[0,2,4]])
print(arr[[4,5]][:,[4,5]])

[3 4]
[ 2 12 22 32 42 52]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [99]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])  # 4 x 3
print(x)
v = np.array([1, 0, 1])
print("타일출력")
print("==========")
vv = np.tile(v, (4, 1))  # v를 행으로 4번 , 열로 1번 복사
print(vv)
print("==========")
y = x + vv            # 4x3 배열연산 => 요소별 연산
print(y)
print("==========")
#배열 연산은 양쪽 차원이 일치해야함 
print(x+v)          # 4x3, 1x3  => broadcasting  자동으로 4개의 행을 만들고 더함
print("==========")
print(x+3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [103]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 ( 행열곱 )   :  x@x로 표현
# 앞의 행렬 열수와 뒤의 행렬의 행수가 일치해야함
#x@x  -> 오류

#전치 행렬
#행, 열을 바꿈
print(x.T)
print("=========")
print(x@x.T)  # 3x2 @ 2x3  ==> 3x3
print("=========")
print(x.T@x)  # 2x3 @ 3x2  = => 2x2

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]
[[20 26]
 [26 35]]


In [107]:
arr = np.arange(24).reshape((2,3,4))  # 2 x 3 x 4
print(arr)
print("====================")
print(arr.transpose((1,0,2)))  # 3 x 2 x 4   # reshape의 순서를 바꾸는 것
print("====================")
print(arr.transpose((0,2,1)))  # 2 x 4 x 3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [114]:
#Boolean indexing

names = np.array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju', 'Daejun','Daejun'])
data = np.random.randn(7,4)
print(data)
print("==============================================")
print(names == "Seoul")  # 1,0,0,0,0,0,0
print("==============================================")

print(data[names =='Seoul'])  # data[1,0,0,0,0,0,0]
print("==============================================")

print(data[names == 'Seoul', 2:])
print("==============================================")

print(data[names == 'Seoul', 3])
print("==============================================")

print(names !="Seoul")
print("==============================================")

print(~(names =="Seoul"))
print("==============================================")

mask = (names == 'Seoul') | (names == 'chungju')
print(mask)
print("==============================================")
print(data[mask])
print("==============================================")

[[-1.24570006  0.6650896   0.25573338  0.12042048]
 [ 0.63076374  0.68793789 -2.07268781 -0.64010509]
 [ 0.85655303  0.78175889  0.76209351 -0.38384254]
 [-0.33601514 -0.00784156 -0.15593101  1.72923317]
 [ 0.95055066  0.01923973 -1.16147267 -0.43802184]
 [-0.4059219  -0.53592083  0.14123869  1.9299183 ]
 [-0.98131038  1.17257206 -0.47086933 -0.16103355]]
[ True False False False False False False]
[[-1.24570006  0.6650896   0.25573338  0.12042048]]
[[0.25573338 0.12042048]]
[0.12042048]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[-1.24570006  0.6650896   0.25573338  0.12042048]
 [ 0.85655303  0.78175889  0.76209351 -0.38384254]
 [ 0.95055066  0.01923973 -1.16147267 -0.43802184]]


In [126]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True , False])
print(zip(xarr, yarr, cond))  # 요소별(index)로 데이터를 묶어줌 
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]  # 삼항 연산자
print("result = ", result)

#== 같은 값
result = np.where(cond, xarr, yarr)  # cond가 참이면 xarr/ 거짓이면 yarr
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[ 1.40856511 -0.57231943 -1.24740522  0.27423102]
 [-1.70230574 -0.74981215 -1.09416372 -1.36201154]
 [-0.33994182  0.3333309  -0.96291261 -1.22563397]
 [-0.23616328  1.39981331 -0.55895198 -0.29524369]]
[[ 2 -2 -2  2]
 [-2 -2 -2 -2]
 [-2  2 -2 -2]
 [-2  2 -2 -2]]


In [131]:
# 문제 ) 다음 데이터를 이용하여 두개 다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일때는
# 2, 그외 일대는 3으로 처리하여 출력하시요
result = []
cond1 = np.array([1,0,1,1,0,0,1],dtype = bool)
cond2 = np.array([0,1,1,1,0,1,1],dtype = bool)
print(cond1)
print(cond2)
np.where(cond1,np.where(cond2,0,1),np.where(cond2,2,3))
# np.where(cond1 & cond2, 0 , np.where(cond1, 1, np.where(cond2, 2,3)))


[ True False  True  True False False  True]
[False  True  True  True False  True  True]


array([1, 2, 0, 0, 3, 2, 0])

In [132]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x)  # x와 형태가 같은 사이즈로 초기화
for i in range(10000) :
    z[i] = x[i] + y[i]

In [134]:
a = np.array([1,2,3,4])
b=  np.array([4,2,2,4])
print(np.all(a == b))  # 전체가 참일 때 True
print(np.any(a == b))  # 하나라도 참일 때 True
print(np.exp(a))  # 지수함수 ( 자연대수 :2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# 선형대수 : 선형으로 문제를 해결 => 비선형도 잘게 나누면 선형

In [ ]:
# 행렬의 종류 
# - 정방행렬 : 정사각형 ( 행과 열 수가 같음 )
# - 대칭행렬 : 우상단과 좌하단이 같은 행렬 
# - 대각행렬 : scale을 변화시키는 행렬
# - 단위행렬( identity ) : 행렬곱의 항등원 # 행렬과 역행렬을 곱하면 단위행렬
# - 역행렬 : 행렬의 나눗셈을 위해 구해서 곱해지는 행렬 ( 정방행렬만 가능 )
# - 특이행렬 : 역행렬이 없는 행렬
# - 직교행렬 : 축의 정직교, 각 축간의 내적이 0인 행렬
# - 정방행렬이면서 대칭행렬 : 공분산행렬, 산관계수행렬, 거리행렬
# - 공분산 : 두수간의 관계 ((한수-평균) * (다른수-평균)) / (n-1)
# - 상관계수(표준화  -1 ~ 1) : 공분산 / 표준편차의 곱

In [136]:
import numpy as np
f1 = np.array([[1,2],[3,4]])
f2 = np.array([[2,2],[2,2]])
print(f1)
print("============")
print(f2)
print("============")
print( f1 + f2 )   # 요소끼리
print("============")
print( f1 * f2)    # 요소끼리
print("============")
print( f1 @ f2)    # 행렬곱(내적)


[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [138]:
# 방정식의 해
# 2x1 + x2 -2x3 = -3
# 3x1 +     x3 = 5
#  x1 + x2 - x3 = -2
A =  np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b = np.transpose(np.a
                 
                 
                 

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [139]:
# x와 같은 식
np.dot(np.linalg.inv(A),b)  #dot : 행렬곱
np.linalg.inv(A)@b #inv : 역행렬 함수  ( 행렬은 나눗셈이 없기때문에 역행렬 곱하여 해결 )

array([[ 1.],
       [-1.],
       [ 2.]])

In [140]:
a = np.array([0,1,0])
b = np.array([1,0,0])
res = np.dot(a,b)  # 내적 사이각 : 직각
print(res)

0


In [142]:
print(np.linalg.norm(a))  # 벡터의 크기
print(np.linalg.norm(b))  
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b))   #cos(theta)값
print("cos theta" , rad)
print(np.arccos(rad)) # theta 값(라디안)
print(np.degrees(np.arccos(rad))) #각도(degree)

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [144]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [156]:
# 문제 : 다음 방정식의 해를 구하고 검산하세요
# x   + y + z = 6
#     2y + 5z = -4
# 2x + 5y - z = 27

A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print(A)
B = np.transpose(np.array([[6,-4,27]]))
print(B)
C = np.linalg.solve(A,B)
C = np.dot(np.linalg.inv(A),B)
C = np.linalg.inv(A)@B
print(C)
print(5 + 3 -2 )
print(0 + 2*3 + (-2)*5)
print(2*5 + 5*3 + 2)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]
6
-4
27
